export const SUPPORTED_LANGUAGES = {
  en: { name: "English", nativeName: "English", dir: "ltr" as const },
  ru: { name: "Russian", nativeName: "Русский", dir: "ltr" as const },
  de: { name: "German", nativeName: "Deutsch", dir: "ltr" as const },
  he: { name: "Hebrew", nativeName: "עברית", dir: "rtl" as const },
  fr: { name: "French", nativeName: "Français", dir: "ltr" as const },
} as const;

export type SupportedLanguageCode = keyof typeof SUPPORTED_LANGUAGES;

export const SMS_TEMPLATES: Record<SupportedLanguageCode, string> = {
  en: "[GoaSafe] Complaint #{number} registered. A tourism officer will contact you within 4 hours. Track: {url} Helpline: 1800-123-4567",
  ru: "[GoaSafe] Жалоба #{number} зарегистрирована. Сотрудник туризма свяжется с вами в течение 4 часов. Статус: {url}",
  de: "[GoaSafe] Beschwerde #{number} registriert. Ein Tourismusbeamter wird Sie innerhalb von 4 Stunden kontaktieren. Status: {url}",
  he: "[GoaSafe] תלונה #{number} נרשמה. פקיד תיירות ייצור איתך קשר תוך 4 שעות. מצב: {url}",
  fr: "[GoaSafe] Plainte #{number} enregistrée. Un agent du tourisme vous contactera dans les 4 heures. Suivi: {url}",
};

export const UI_TRANSLATIONS: Record<SupportedLanguageCode, Record<string, string>> = {
  en: {
    appTitle: "GoaSafe — Tourist Safety",
    submitComplaint: "Report an Incident",
    yourName: "Your Name",
    phoneNumber: "Phone Number",
    email: "Email (optional)",
    nationality: "Nationality",
    describeIncident: "Describe the Incident",
    vehicleNumber: "Taxi/Vehicle Number (if known)",
    incidentLocation: "Where did this happen?",
    fareCharged: "Amount Charged (₹)",
    submit: "Submit Report",
    trackStatus: "Track Complaint Status",
    complaintNumber: "Complaint Number",
    selectLanguage: "Select Language",
    uploadEvidence: "Upload Photos/Videos",
    incidentDate: "When did this happen?",
    submitting: "Submitting...",
    successTitle: "Complaint Registered",
    successMessage: "You will receive an SMS confirmation shortly.",
    errorTitle: "Submission Failed",
    errorMessage: "Please try again or call our helpline.",
  },
  ru: {
    appTitle: "GoaSafe — Безопасность туристов",
    submitComplaint: "Сообщить об инциденте",
    yourName: "Ваше имя",
    phoneNumber: "Номер телефона",
    email: "Email (необязательно)",
    nationality: "Гражданство",
    describeIncident: "Опишите инцидент",
    vehicleNumber: "Номер такси (если известен)",
    incidentLocation: "Где это произошло?",
    fareCharged: "Сумма оплаты (₹)",
    submit: "Отправить жалобу",
    trackStatus: "Проверить статус жалобы",
    complaintNumber: "Номер жалобы",
    selectLanguage: "Выберите язык",
    uploadEvidence: "Загрузить фото/видео",
    incidentDate: "Когда это произошло?",
    submitting: "Отправка...",
    successTitle: "Жалоба зарегистрирована",
    successMessage: "Вы получите SMS-подтверждение в ближайшее время.",
    errorTitle: "Ошибка отправки",
    errorMessage: "Попробуйте снова или позвоните на горячую линию.",
  },
  de: {
    appTitle: "GoaSafe — Touristensicherheit",
    submitComplaint: "Vorfall melden",
    yourName: "Ihr Name",
    phoneNumber: "Telefonnummer",
    email: "E-Mail (optional)",
    nationality: "Nationalität",
    describeIncident: "Beschreiben Sie den Vorfall",
    vehicleNumber: "Taxi-/Fahrzeugnummer (falls bekannt)",
    incidentLocation: "Wo ist es passiert?",
    fareCharged: "Berechneter Betrag (₹)",
    submit: "Bericht einreichen",
    trackStatus: "Beschwerdestatus prüfen",
    complaintNumber: "Beschwerdenummer",
    selectLanguage: "Sprache wählen",
    uploadEvidence: "Fotos/Videos hochladen",
    incidentDate: "Wann ist es passiert?",
    submitting: "Wird gesendet...",
    successTitle: "Beschwerde registriert",
    successMessage: "Sie erhalten in Kürze eine SMS-Bestätigung.",
    errorTitle: "Übermittlung fehlgeschlagen",
    errorMessage: "Bitte versuchen Sie es erneut oder rufen Sie unsere Hotline an.",
  },
  he: {
    appTitle: "GoaSafe — בטיחות תיירים",
    submitComplaint: "דווח על אירוע",
    yourName: "השם שלך",
    phoneNumber: "מספר טלפון",
    email: "אימייל (אופציונלי)",
    nationality: "לאום",
    describeIncident: "תאר את האירוע",
    vehicleNumber: "מספר מונית (אם ידוע)",
    incidentLocation: "איפה זה קרה?",
    fareCharged: "סכום שנגבה (₹)",
    submit: "שלח דיווח",
    trackStatus: "עקוב אחר סטטוס התלונה",
    complaintNumber: "מספר תלונה",
    selectLanguage: "בחר שפה",
    uploadEvidence: "העלה תמונות/סרטונים",
    incidentDate: "מתי זה קרה?",
    submitting: "שולח...",
    successTitle: "התלונה נרשמה",
    successMessage: "תקבל אישור ב-SMS בקרוב.",
    errorTitle: "השליחה נכשלה",
    errorMessage: "נסה שוב או התקשר לקו החם.",
  },
  fr: {
    appTitle: "GoaSafe — Sécurité des touristes",
    submitComplaint: "Signaler un incident",
    yourName: "Votre nom",
    phoneNumber: "Numéro de téléphone",
    email: "Email (optionnel)",
    nationality: "Nationalité",
    describeIncident: "Décrivez l'incident",
    vehicleNumber: "Numéro du taxi (si connu)",
    incidentLocation: "Où cela s'est-il produit ?",
    fareCharged: "Montant facturé (₹)",
    submit: "Soumettre le signalement",
    trackStatus: "Suivre le statut de la plainte",
    complaintNumber: "Numéro de plainte",
    selectLanguage: "Choisir la langue",
    uploadEvidence: "Télécharger photos/vidéos",
    incidentDate: "Quand cela s'est-il produit ?",
    submitting: "Envoi en cours...",
    successTitle: "Plainte enregistrée",
    successMessage: "Vous recevrez une confirmation par SMS sous peu.",
    errorTitle: "Échec de l'envoi",
    errorMessage: "Veuillez réessayer ou appeler notre ligne d'assistance.",
  },
};
